name: ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.1	

flutter:
  uses-material-design: true
  assets:
    - lib/components/Google.png
    - lib/components/magic-hands.png
    - lib/components/scooter.png
    - lib/components/package.png
    - lib/components/rexa.png
    - lib/components/receipt.png
    - lib/components/Sneakers/Nike-1.jpg
    - lib/components/Sneakers/Nike-2.jpg
    - lib/components/Sneakers/Nike-3.jpg
    - lib/components/Sneakers/Nike-4.jpg
    - lib/components/Sneakers/Nike-5.jpg
    - lib/components/Sneakers/Nike-6.jpg
    - lib/components/Bottom-NavIcon/NavIcon-1.png
    - lib/components/Bottom-NavIcon/NavIcon-2.png
    - lib/components/Bottom-NavIcon/NavIcon-3.png
    - lib/components/Bottom-NavIcon/NavIcon-4.png
    - lib/components/Men-Images/Nike-1.jpg
    - lib/components/Men-Images/Nike-2.jpg
    - lib/components/Men-Images/Nike-3.jpg
    - lib/components/Men-Images/Nike-4.jpg
    - lib/components/Product-Images/spider.png