name: ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.1	

flutter:
  uses-material-design: true
  assets:
    - lib/components/Google.png
    - lib/components/magic-hands.png
    - lib/components/scooter.png
    - lib/components/package.png
    - lib/components/rexa.png